version: '2'
services:
  mysql:
    image: r.qihoo.cloud/library/mysql:5.6.36
    container_name: ${DEV_USER}-mysql
    command: --character-set-server=utf8mb4
    environment:
      MYSQL_DATABASE: "indole"
      MYSQL_ROOT_PASSWORD: "a1b2c3d4e"
    volumes:
      - ./_dev/mysql:/var/lib/mysql:z
    expose:
      - "3306"
    ports:
      - "${DEV_DB_PORT}:3306"
  smtp:
    image: r.qihoo.cloud/docker.io/tianon/exim4:latest
    expose:
      - "25"
    ports:
      - "${DEV_SMTP_PORT}:25"
